name: DevSecOps Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

jobs:

  # ----------------------------
  # Secret Scan (Gitleaks)
  # ----------------------------
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 \
            -o /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks
      - name: Run Gitleaks (current branch)
        run: gitleaks detect --source . --redact --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true
      - name: Run Gitleaks (full history)
        run: gitleaks detect --source . --log-opts="--all" --redact --report-format sarif --report-path history.sarif
        continue-on-error: true
      - name: Upload Gitleaks Reports
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-reports
          path: |
            gitleaks.sarif
            history.sarif


  # ----------------------------
  # SCA-SBOM Generation & FS Scan
  # ----------------------------
  sca-scan:
    runs-on: ubuntu-latest
    needs: [secret-scan]
    steps:
      - uses: actions/checkout@v3
      - name: SBOM Generation (codenotary)
        uses: codenotary/sbom.sh-create@main
        with:
          scan_type: 'grypefs'
          target: '.'
      - name: Save SBOM to file
        run: echo "$SBOM_SHARE_URL" > sbom-url.txt
      - name: Upload SBOM Report
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom-url.txt

  # ----------------------------
  # SAST-Bandit Scan
  # ----------------------------
  sast-bandit:
    runs-on: ubuntu-latest
    needs: [secret-scan]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install bandit
      - name: Bandit Scan
        run: |
          mkdir -p artifacts
          bandit -r ./src -f json -o artifacts/bandit-report.json
        continue-on-error: true
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: artifacts/bandit-report.json

  # ----------------------------
  # SAST-SonarQube Scan
  # ----------------------------
  sast-sonarqube:
    runs-on: ubuntu-latest
    needs: [secret-scan]
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        continue-on-error: true

  # ----------------------------
  # Final Build & Push (with Ruff)
  # ----------------------------
  docker-build:
    runs-on: ubuntu-latest
    needs: [sca-scan, sast-bandit, sast-sonarqube]   # waits for all scans (including secret-scan indirectly)
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install ruff

      - name: Ruff Lint Fix
        run: ruff check --fix .
        continue-on-error: true

      - name: Ruff Format
        run: ruff format .
        continue-on-error: true

      - name: Set Image Tags
        id: tagger
        run: |
          echo "tag=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "latest=latest" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image (with auto tag and latest)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sentinelv2:${{ steps.tagger.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/sentinelv2:latest
