name: DevSecOps Pipeline (Consumer)

on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

jobs:
  devsecops:
    uses: exrienz/secops-template/.github/workflows/devsecops.yml@main
    with:
      enable_sca: true
      enable_sonarqube: true
      enable_docker_build: true
      languages: 
        - python
        - javascript
    secrets: inherit
