name: DevSecOps Pipelines

on:
  push:
    branches: [main, develop]

jobs:
  devsecops:
    uses: exrienz/secops-template/.github/workflows/devsecops.yml@main
    with:
      enable_sca: true
      enable_sast: true
      enable_docker_build: true
      enable_container_scan: true
      languages: "python,javascript"
    secrets: inherit
